### ISSUE TITLE
Create Azure Service Principal

### ISSUE THREAD

**Issue by mtarng** [yradsmikham/bedrock-cli#3]
As a developer, I can run `bedrock create az-sp` and a sample service principal will be created.

Low priority, this just reduces looking up az-cli documentation

**Comment by yradsmikham** [comment]
Do we want to support this or should we make the expectation that users will bring their own SP?

**Comment by mtarng** [comment]
i think this is just a simple ticket. it just calls `az ad sp create-for-rbac --subscription <subscription>`. But this is used to get a service principal that we can track for the cluster. BYOSP or have the cli create one, i'm okay with either.

**Comment by yradsmikham** [comment]
Discussed this with Jim. For now, let's settle with a "BYO" Service Principal.
