### ISSUE TITLE
Create `bedrock populate` path

### ISSUE THREAD

**Issue by mtarng** [yradsmikham/bedrock-cli#7]
As a user, I should be able to populate all .tfvars files via the cli.

Options for doing so:

1. Populate all fields via auto-generation (where possible)
2. Guided interactive CLI
3. A single file with the list of variables.

Consider what variables are listed in all `*variables.tf` files, and what is provided in default `terraform.tfvars` and `backend.tfvars` files (if they exist)

**Comment by edaena** [comment]
Sounds like 1. will be supported by the bedrock demo scenario #4 
And we should support 3.
Those two seem good for the purpose of the hack

**Comment by yradsmikham** [comment]
Yes, Option 1 is supported as part of `demo.go`. Let's give Option 3 a shot. :)

**Comment by edaena** [comment]
Based on what we talked, we won't have a dedicated populate command. Instead the logic to apply default values will be in the simulate command.

**Comment by yradsmikham** [comment]
Closing this for now since we have gone with a different approach. Will revisit this in the future!
