### ISSUE TITLE
demo.go should check to see if Bedrock repo is already cloned

### ISSUE THREAD

**Issue by yradsmikham** [yradsmikham/bedrock-cli#9]

**Comment by mtarng** [comment]
Might be able to avoid cloning the full repo:
https://github.com/HR/github-clone
or
https://github.blog/changelog/2018-11-08-git-protocol-v2-support/
https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/52269934#52269934

**Comment by yradsmikham** [comment]
For now, I have the `demo.go` check to see if the current working directory already has the bedrock repo, and if it does, then it moves on to the next step.

However, I like the idea of using HR/Github-clone. I think that could be a potential long-term solution.

Closing this for now.
